Homework 6
================
Marisa Sobel
11/16/2018

# Problem 1

### DATA IMPORT AND TIDY

``` r
wp_homicide_data = 
  read_csv("./data/data-homicides-master/homicide-data.csv", na = c("", "Unknown", "NA")) %>% 
  mutate(city_state = str_c(city, state, sep = ", ")) %>% 
  filter(!city_state %in% c("Dallas, TX", "Pheonix, AZ", "Kansas City, MO", "Tulsa, AL")) %>% 
  filter(victim_race != "NA") %>% 
  filter(victim_age != "NA") %>% 
  filter(victim_sex != "NA") %>% 
  mutate(
    victim_race = as_factor(case_when(
      victim_race == "White" ~ "white", 
      victim_race != "white" ~ "non-white")), 
    victim_race = fct_relevel(victim_race, "white"),
    victim_sex = as_factor(tolower(victim_sex)), 
    victim_sex = fct_relevel(victim_sex, "female"), 
    victim_age = as.numeric(victim_age),
    outcome = as_factor(case_when(
      disposition == "Closed by arrest" ~ "resolved",
      disposition == "Closed without arrest" ~ "unresolved", 
      disposition == "Open/No arrest" ~ "unresolved"))) %>% 
  select(-uid, -reported_date, -victim_first, -victim_last, -lat, -lon, -city, -state, -disposition)

wp_homicide_data
## # A tibble: 47,535 x 5
##    victim_race victim_age victim_sex city_state      outcome   
##    <fct>            <dbl> <fct>      <chr>           <fct>     
##  1 non-white           78 male       Albuquerque, NM unresolved
##  2 non-white           17 male       Albuquerque, NM resolved  
##  3 white               15 female     Albuquerque, NM unresolved
##  4 non-white           32 male       Albuquerque, NM resolved  
##  5 white               72 female     Albuquerque, NM unresolved
##  6 white               91 female     Albuquerque, NM unresolved
##  7 non-white           52 male       Albuquerque, NM resolved  
##  8 non-white           52 female     Albuquerque, NM resolved  
##  9 white               56 male       Albuquerque, NM unresolved
## 10 non-white           43 male       Albuquerque, NM unresolved
## # ... with 47,525 more rows
```

The original dataset had 52,169 entries. 2758 entries were removed from
cities that did not have race data in full (“Dallas, TX”, “Pheonix, AZ”,
“Kansas City, MO”, “Tulsa, AL”). 1442 entries were removed for missing
race information, 391 entries were removed for missing age information,
and 53 entries were removed for missing sex information.

Victim race is coded as binary as white and non-white, with white as the
reference category.  
Victim sex is coded as binary as female and male, with female as the
refrence category.  
The homicide outcome is coded as binary as resolved and unresolved,
where resolved includes “Closed by arrest” and unresolved includes
“closed without arrest” and “open/no arrest”.

### BALTIMORE, MD

Run `glm` (resolved/unresolved) for Baltimore, MD comparing non-white
victims to white victims and accounting for sex and age.

``` r
# baltimore glm model 
glm_baltimore = 
  wp_homicide_data %>% 
  filter(city_state == "Baltimore, MD") %>% 
  glm(outcome ~ victim_age + victim_sex + victim_race, data = ., family = binomial)

# get OR and CIs
tidy(glm_baltimore, conf.int = TRUE) %>% 
  mutate(OR = exp(estimate), 
         CI_low = exp(conf.low), 
         CI_high = exp(conf.high)) %>% 
  select(term, OR, CI_low, CI_high) %>% 
  filter(term == "victim_racenon-white") %>% 
  knitr::kable(digits = 3)
```

| term                  |    OR | CI\_low | CI\_high |
| :-------------------- | ----: | ------: | -------: |
| victim\_racenon-white | 0.441 |   0.312 |     0.62 |

For the city of Baltimore, MD, the odds of solving homicides among
non-whites is 0.441 (95% CI: 0.312, 0.62) times the odds of solving
homicides among whites. Conversly, the odds of solving homicides among
whites is 2.27 times the odds of solving homicides among non-whites in
Baltimore, MD.

### ALL CITIES

#### GLM (resolved/unresolved)

Run `glm` (resolved/unresolved) for all cities comparing non-white
victims to white victims and accounting for sex and age.

``` r
# all cities glm model 
glm_all_cities = 
  wp_homicide_data %>% 
  group_by(city_state) %>% 
  nest() %>% 
  mutate(
    model = map(data, ~tidy(glm(outcome ~ victim_age + victim_sex + victim_race, 
                                data = ., family = binomial), conf.int = TRUE))) %>% 
  select(-data) %>% 
  unnest()
  
# get OR and CIs
or_all_cities = 
  glm_all_cities %>% 
  mutate(OR = exp(estimate), 
         CI_low = exp(conf.low), 
         CI_high = exp(conf.high)) %>% 
  select(city_state, term, OR, CI_low, CI_high) %>% 
  filter(term == "victim_racenon-white") %>% 
  mutate(city_state = fct_reorder(city_state, OR)) %>% 
  arrange(city_state, desc(OR))

or_all_cities
```

    ## # A tibble: 47 x 5
    ##    city_state     term                    OR CI_low CI_high
    ##    <fct>          <chr>                <dbl>  <dbl>   <dbl>
    ##  1 Boston, MA     victim_racenon-white 0.127 0.0472   0.285
    ##  2 Omaha, NE      victim_racenon-white 0.170 0.0914   0.300
    ##  3 Oakland, CA    victim_racenon-white 0.213 0.0989   0.418
    ##  4 Pittsburgh, PA victim_racenon-white 0.282 0.157    0.485
    ##  5 Cincinnati, OH victim_racenon-white 0.318 0.180    0.541
    ##  6 Stockton, CA   victim_racenon-white 0.376 0.193    0.713
    ##  7 Louisville, KY victim_racenon-white 0.392 0.257    0.590
    ##  8 Buffalo, NY    victim_racenon-white 0.392 0.211    0.714
    ##  9 Baltimore, MD  victim_racenon-white 0.441 0.312    0.620
    ## 10 Fresno, CA     victim_racenon-white 0.445 0.221    0.841
    ## # ... with 37 more rows

Use the `or_all_cities` dataframe to plot ORs and CIs for all cities.

### ALL CITIES

#### Plot - ORs + CIs

``` r
or_all_cities %>% 
  ggplot(aes(x = city_state, y = OR)) +
  geom_hline(aes(yintercept = 1), color = "red") +
  geom_point() +
  geom_errorbar(aes(ymin = CI_low, ymax = CI_high)) + 
  coord_flip() + 
  labs(
    x = "OR (95% CI)", 
    y = "City, State", 
    title = "Solved homicides, comparing non-white victims to white victims")
```

![](p8105_hw6_ms5533_files/figure-gfm/unnamed-chunk-4-1.png)<!-- -->

After adjusting for victim age and sex, the plot above illustrates the
ORs (95% CI) of a homicide being solved comparing non-white victims to
white victims. Most cities have higher odds of homicides being solved if
the victim is white (OR \< 1), except for Tampa, Birmigham, and Durham.
Durham has the largest CI, and there seems to be a trend of larger CIs
the closer the OR gets to 1, the null value for ORs.

# Problem 2

### DATA IMPORT AND TIDY

``` r
birthweight_data = 
  read_csv("./data/birthweight.csv") %>% 
  mutate(
    babysex = factor(babysex, labels = c("male", "female")), 
    frace = factor(frace, labels = c("white", "black", "asian", "puerto_rican", "other", "unknown")))


  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
```
