---
title: "Homework 6"
author: "Marisa Sobel"
date: "11/16/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(modelr)
library(mgcv)
library(broom)
library(boot)
library(modelr)

set.seed(1)

theme_set(theme_bw() + theme(legend.position = "bottom"))
```

# Problem 1

### DATA IMPORT AND TIDY

```{r, collapse=TRUE, message=FALSE}
wp_homicide_data = 
  read_csv("./data/data-homicides-master/homicide-data.csv", na = c("", "Unknown", "NA")) %>% 
  mutate(city_state = str_c(city, state, sep = ", ")) %>% 
  filter(!city_state %in% c("Dallas, TX", "Pheonix, AZ", "Tulsa, AL")) %>% 
  filter(victim_race != "NA" | victim_age != "NA") %>% 
  select(-uid, -reported_date, -victim_first, -victim_last, -lat, -lon, -city, -state) %>% 
  mutate(
    victim_race = as_factor(case_when(
      victim_race == "White" ~ "white", 
      victim_race != "white" ~ "non-white")), 
    victim_race = fct_relevel(victim_race, "white"),
    victim_sex = as_factor(tolower(victim_sex)), 
    victim_sex = fct_relevel(victim_sex, "male"), 
    victim_age = as.numeric(victim_age),
    outcome = as_factor(case_when(
      disposition == "Closed by arrest" ~ "resolved", 
      disposition == "Closed without arrest" ~ "unresolved", 
      disposition == "Open/No arrest" ~ "unresolved")))

wp_homicide_data
```

### BALTIMORE, MD  
#### GLM (resolved/unresolved)

```{r}
# baltimore glm model 
glm_baltimore = 
  wp_homicide_data %>% 
  filter(city_state == "Baltimore, MD") %>% 
  glm(outcome ~ victim_age + victim_sex + victim_race, data = ., family = binomial)

# get OR and CIs
tidy(glm_baltimore, conf.int = TRUE) %>% 
  mutate(OR = inv.logit(estimate), 
         CI_low = inv.logit(conf.low), 
         CI_high = inv.logit(conf.high)) %>% 
  select(term, OR, CI_low, CI_high) %>% 
  filter(term == "victim_racenon-white") %>% 
  knitr::kable(digits = 3)
```

### ALL CITIES  
#### GLM (resolved/unresolved)

```{r}

```

### ALL CITIES
#### Plot - ORs + CIs 

```{r}

```


# Problem 2

### DATA IMPORT AND TIDY

```{r, message=FALSE, collapse=TRUE, eval=FALSE}
birthweight_data = 
  read_csv("./data/birthweight.csv") %>% 
  mutate(
    babysex = factor(babysex, labels = c("male", "female")), 
    frace = factor(frace, labels = c("white", "black", "asian", "puerto_rican", "other", "unknown")))


  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
```

